apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-service
  template:
    metadata:
      labels:
        app: spring-service
        annotations:           # Add this block here
          rollme: "2025-03-01-1"  # Update this value each push

    spec:
      containers:
      - name: spring-service
        image: localhost:5000/spring-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: spring-service
  type: ClusterIP