name: CI Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Debug directory
        run: pwd && ls -la  # Debug what’s cloned
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package -DskipTests  # No cd needed
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        run: |
          docker build -t localhost:5000/spring-service:latest .
          docker push localhost:5000/spring-service:latest
